export default [
    {
        type: "hotels",
        id: 1,
        title: "Mirante do Gavião",
        label: "Mirante do Gavião",
        content: {
            id: "",
            title: "Mirante do Gavião",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: 'https://mirantedogaviao.com.br/br/wp-content/uploads/2021/08/1-Capa-Miniatura-PD1A4962.jpg',
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", ""]
        },
    },
    {
        type: "hotels",
        id: 2,
        title: "Mirante do Gavião",
        label: "Mirante do Gavião",
        content: {
            id: "",
            title: "Mirante do Gavião",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: 'https://images.unsplash.com/photo-1527679124583-9208be990bb5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80',
            prices: '$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
        },
    },
    {
        type: "hotels",
        id: 3,
        title: "Mirante do Gavião",
        label: "Mirante do Gavião",
        content: {
            id: "",
            title: "Mirante do Gavião",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: 'https://mirantedogaviao.com.br/br/wp-content/uploads/2021/08/1-Capa-Miniatura-PD1A4962.jpg',
            prices: ["$", "$$", "$$$", "$$$$"],
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
        },
    },
]