export default [
    {
        type: "road",
        id: 0,
        title: "Centro Ecológico Ekobé",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "road",
        id: 1,
        title: "Pesque-pague Anavilhanas",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "road",
        id: 2,
        title: "Balneário do Mator Grosso",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "inCity",
        id: 10,
        title: "Artesanato da FAM",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/inCity/fam.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "inCity",
        id: 11,
        title: "Casa Ateliê",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/inCity/buy.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "inCity",
        id: 12,
        title: "Flutuante dos Botos",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/inCity/botos.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "anavilhanas",
        id: 20,
        title: "Árvores gigantes",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/anavilhanas/tree.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "anavilhanas",
        id: 21,
        title: "Focagem Noturna",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/anavilhanas/nightFocus.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "anavilhanas",
        id: 22,
        title: "Observações de aves",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/anavilhanas/bird.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "jau",
        id: 30,
        title: "Petroglifos",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/jau/petroglifo.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "jau",
        id: 31,
        title: "Cachoeira do Jáu",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/jau/cachoeira.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "jau",
        id: 32,
        title: "Trilhas da mata",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/jau/trilha.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "river",
        id: 40,
        title: "Ruínas de Velho Airão",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "river",
        id: 41,
        title: "Trilha e gruta do Madadá",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "river",
        id: 42,
        title: "Trilhas e pernoites na selva",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "toEat",
        id: 50,
        title: "Matupá Bar",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/toEat/matupa.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "toEat",
        id: 51,
        title: "Restaurante Sabor do Sul",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/toEat/saborDoSul.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "toEat",
        id: 52,
        title: "Restaurante Flor do Luar",
        content: {
            id: "",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require('./exceptionalImage/toEat/florDoLuar.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "hotels",
        id: 600,
        title: "Pousada Novo Airâo",
        content: {
            description: "Somos uma pousada aconchegante, sossegada, ambiente familiar, com ótimas instalações pra receber você e sua família!",
            image: require('./exceptionalImage/hotels/pousadaNovoAirao.jpg'),
            contacts: "9298468-9749",
            social: {
                instagram: 'https://www.instagram.com/pousadanovoairao/',
                facebook: '',
                site: ''
            },
            offering: ["Internet", "Estacionamento", "Piscina", "Café da Manhã"],
            address: "R. Naíde Batista, 35, Horizonte",
            type: 'diária',
            workingHour: "",
            profile: ["adventure", "soft", "calm"],
            duration: "",
            prices: '1317',
            id: "",
        },
    },
    {
        type: "hotels",
        id: 601,
        title: "Pousada Paraíso",
        content: {
            description: "Nós oferecemos uma segunda casa para as pessoas, com uma hospedagem segura e confortável, servindo à todos que quiserem se hospedar com segurança e tranquilidade. Damos aos viajantes a garantia de que podem andar pela cidade com tranquilidade, que terão onde descansar e relaxar.",
            image: require('./exceptionalImage/hotels/pousadaParaiso.jpg'),
            contacts: "(92) 98412-1122",
            social: {
                instagram: "https://instagram.com/pousadaparaisoairao?igshid=YmMyMTA2M2Y=",
                facebook: '',
                site: "https://website--1236236308606472178244-inn.negocio.site/?utm_source=gmb&utm_medium=referral",
            },
            offering: ["Internet", "Estacionamento"],
            address: "",
            type: 'diária',
            workingHour: "",
            profile: ["adventure", "soft", "calm"],
            duration: "",
            prices: '1317',
            id: "",
        },
    },
    {
        type: "hotels",
        id: 602,
        title: "Bela Vista",
        content: {
            description: "Estamos localizados num sítio por volta de 11mil m² na margem do majestoso Rio Negro no centro do paraíso ecológico Novo Airão, que fica a aproximadamente 190km de Manaus. Com as melhores acomodações em um local charmoso e aconchegante, bem à frente do rio com uma vista, encantamos todos que por aqui se hospedam.",
            image: require('./exceptionalImage/hotels/pousadaBelaVista.jpg'),
            contacts: ["+55 (92) 3365-1023"],
            social: {
                instagram: 'https://www.instagram.com/belavistalodge/',
                facebook: 'https://www.facebook.com/pousada.belavista.amazonas',
                site: "https://www.pousada-belavista.com"
            },
            offering: ["internet", "vista para o rio", "estacionamento", "piscina", "café da manhã", "flutuante", "deck com acesso ao rio", "passeios e expedições", "casas de temporada", "restaurante", "bar", "área de lazer."],
            address: "",
            type: 'diária',
            workingHour: "",
            profile: ["adventure", "soft", "calm"],
            duration: "",
            prices: '1317',
            id: "",
        },
    },
    {
        type: "hotels",
        id: 603,
        title: "Pousada Cabloca",
        content: {
            description: "Pousada Cabocla, fica localizada na Rua Rui Barbosa, centro n° 52, cidade de Novo Airão, próximo a praça do dinossauro, restaurantes, café da manhã, supermercado, drogarias e fórum. Contempla uma área ampla para os clientes ficarem a vontade, os apartamentos são equipados com ar condicionado e TVs a cabo.",
            image: require('./exceptionalImage/hotels/pousadaCabocla.jpg'),
            contacts: ["(92) 99235-7141"],
            social: {
                instagram: '',
                facebook: '"https://web.facebook.com/caboclapousada"',
                site: ''
            },
            offering: ["Internet, estacionamento."],
            address: "",
            type: 'diária',
            workingHour: "",
            profile: ["adventure", "soft", "calm"],
            duration: "",
            prices: '1317',
            id: "",
        },
    },
    {
        type: "hotels",
        id: 604,
        title: "Lodge Mirante do Gavião",
        content: {
            description: "É um Hotel Luxo Designer, com área de lazer (piscina, salão de jogos, mirantes, etc), restaurante, passeios. Sua arquitetura é exclusiva, voltada para homenagear a cultura local. Às estruturas das suítes parecem casco do barco invertido. ",
            image: require('./exceptionalImage/hotels/miranteGaviao.jpg'),
            contacts: ["(92) 991146038"],
            social: {
                instagram: "https://instagram.com/mirantedogaviao?igshid=YmMyMTA2M2Y=",
                facebook: "https://www.facebook.com/mirantedogaviao/",
                site: "https://mirantedogaviao.com.br/br/"
            },
            offering: ["Internet, estacionamento."],
            address: "",
            type: 'diária',
            workingHour: "",
            profile: ["adventure", "soft", "calm"],
            duration: "",
            prices: '1317',
            id: "",
        },
    },
    {
        type: "hotels",
        id: 605,
        title: "Amazon Park Suítes",
        content: {
            description: " Somos uma pousada de charme  situada no município de Novo Airão, à 2h30 de Manaus. A estrutura dispõe de 20 apartamentos com vista panorâmica, restaurante com pratos regionais, área para eventos, piscina e trilha, além de uma vasta área verde, cenário perfeito para quem visita à região.",
            image: require('./exceptionalImage/hotels/amazonParkSuite.jpg'),
            contacts: ["(92) 99159-1082"],
            social: {
                instagram: 'https://www.instagram.com/amazonia.parksuites/',
                facebook: '',
                site: "https://amazoniaparksuites.com.br/"
            },
            offering: ["internet", "vista para o rio", "estacionamento", "piscina", "café da manhã", "passeios"],
            address: "",
            type: 'diária',
            workingHour: "",
            profile: ["adventure", "soft", "calm"],
            duration: "",
            prices: '1317',
            id: "",
        },
    },
    {
        type: "adventure",
        id: 70,
        title: "Arborismo",
        content: {
            id: "",
            title: "Arborismo",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require("./exceptionalImage/adventure/arborismo.png"),
            prices: '400',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: "pessoa",
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "adventure",
        id: 71,
        title: "Bike aquática",
        content: {
            id: "",
            title: "Bike aquática",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require("./exceptionalImage/adventure/BikeAquatica.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: "pessoa",
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "adventure",
        id: 72,
        title: "SUP",
        content: {
            id: "",
            title: "SUP",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require("./exceptionalImage/adventure/SUP.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: "pessoa",
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "adventure",
        id: 73,
        title: "Trilha",
        content: {
            id: "",
            title: "Trilha",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require("./exceptionalImage/adventure/trilha.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: "pessoa",
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "tour",
        id: 80,
        title: "Parque Anavilhanas",
        content: {
            id: "",
            title: "Trilha",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require("./exceptionalImage/tour/Anavilhanas.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: "pessoa",
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    }, {
        type: "tour",
        id: 81,
        title: "Parque Jáu",
        content: {
            id: "",
            title: "Trilha",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            image: require("./exceptionalImage/tour/jau.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: "pessoa",
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    }, {
        type: "tour",
        id: 82,
        title: "Reserva Unini",
        content: {
            id: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
            title: "Trilha",
            description: "",
            image: require("./exceptionalImage/tour/unini.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: "pessoa",
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
]