export default [
    {
        type: "road",
        id: 0,
        title: "Centro Ecológico Ekobé",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "road",
        id: 1,
        title: "Pesque-pague Anavilhanas",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "road",
        id: 2,
        title: "Balneário do Mator Grosso",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "inCity",
        id: 10,
        title: "Artesanato da FAM",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/inCity/fam.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "inCity",
        id: 11,
        title: "Casa Ateliê",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/inCity/buy.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "inCity",
        id: 12,
        title: "Flutuante dos Botos",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/inCity/botos.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "anavilhanas",
        id: 20,
        title: "Árvores gigantes",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/anavilhanas/tree.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "anavilhanas",
        id: 21,
        title: "Focagem Noturna",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/anavilhanas/nightFocus.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },    
    {
        type: "anavilhanas",
        id: 22,
        title: "Observações de aves",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/anavilhanas/bird.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "jau",
        id: 30,
        title: "Petroglifos",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/jau/petroglifo.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "jau",
        id: 31,
        title: "Cachoeira do Jáu",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/jau/cachoeira.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "jau",
        id: 32,
        title: "Trilhas da mata",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/jau/trilha.jpg'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "river",
        id: 40,
        title: "Ruínas de Velho Airão",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "river",
        id: 41,
        title: "Trilha e gruta do Madadá",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "river",
        id: 42,
        title: "Trilhas e pernoites na selva",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "toEat",
        id: 50,
        title: "Matupá Bar",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/toEat/matupa.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "toEat",
        id: 51,
        title: "Restaurante Sabor do Sul",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/toEat/saborDoSul.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "toEat",
        id: 52,
        title: "Restaurante Flor do Luar",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/toEat/florDoLuar.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "hotels",
        id: 60,
        title: "Mirante do Gavião",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/hotels/mirante.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "hotels",
        id: 61,
        title: "Pousada Bela Bista",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/hotels/belaVista.png'),
            prices: '$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "hotels",
        id: 62,
        title: "Anavilhanas Jungle Lodge",
        content: {
            id: "",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require('./exceptionalImage/hotels/belaVista.png'),
            prices: '$$$$',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "adventure",
        id: 70,
        title: "Arborismo",
        content: {
            id: "",
            title: "Arborismo",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require("./exceptionalImage/adventure/arborismo.png"),
            prices: '400',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "adventure",
        id: 71,
        title: "Bike aquática",
        content: {
            id: "",
            title: "Bike aquática",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require("./exceptionalImage/adventure/BikeAquatica.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "adventure",
        id: 72,
        title: "SUP",
        content: {
            id: "",
            title: "SUP",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require("./exceptionalImage/adventure/SUP.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "adventure",
        id: 73,
        title: "Trilha",
        content: {
            id: "",
            title: "Trilha",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require("./exceptionalImage/adventure/trilha.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
    {
        type: "tour",
        id: 80,
        title: "Parque Anavilhanas",
        content: {
            id: "",
            title: "Trilha",
            description: "Aproveite nosso espaço visitando o restaurante, subindo no mirante ou então faça um passeio pelas Anavilhanas no nosso barco.",
            image: require("./exceptionalImage/tour/Anavilhanas.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    }, {
        type: "tour",
        id: 81,
        title: "Parque Jáu",
        content: {
            id: "",
            title: "Trilha",
            description: "",
            image: require("./exceptionalImage/tour/jau.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    }, {
        type: "tour",
        id: 82,
        title: "Reserva Unini",
        content: {
            id: "",
            title: "Trilha",
            description: "",
            image: require("./exceptionalImage/tour/unini.png"),
            prices: '150',
            workingHour: "",
            contacts: ["92912345678"],
            address: "Rua Antenor Carlos Francisco",
            type: ["", ""],
            offering: ["7 quartos", "1 refeitório", "1 piscina", "1 deck"],
            duration: "",
            profile: ["adventure", "soft", "calm"]
        },
    },
]